export const latestAds = [
  {
    id: 5,
    title: "Beautiful 2BHK Apartment",
    price: "₹22,000 / Month",
    location: "Noida",
    category: "Real Estate",
    image: "/images/ads/house.jpg",
    posted: "Today",
    featured: false,
  },
  {
    id: 6,
    title: "Maruti Suzuki Swift",
    price: "₹5,50,000",
    location: "Delhi",
    category: "Vehicles",
    image: "/images/ads/car.jpg",
    posted: "Today",
    featured: false,
  },
  {
    id: 7,
    title: "Professional Home Tuition",
    price: "₹2,000 / Month",
    location: "Lucknow",
    category: "Education",
    image: "/images/ads/tuition.jpg",
    posted: "1 day ago",
    featured: false,
  },
  {
    id: 8,
    title: "Experienced Web Developer",
    price: "Starting ₹999",
    location: "Bangalore",
    category: "Services",
    image: "/images/ads/job.jpg",
    posted: "2 days ago",
    featured: false,
  },
];