export const featuredAds = [
  {
    id: 1,
    title: "Luxury Apartment for Rent",
    price: "₹18,000 / Month",
    location: "Delhi",
    category: "Real Estate",
    image: "/images/ads/house.png",
    posted: "2 days ago",
    featured: true,
  },
  {
    id: 2,
    title: "Honda City 2022",
    price: "₹8,50,000",
    location: "Mumbai",
    category: "Vehicles",
    image: "/images/ads/car.png",
    posted: "5 days ago",
    featured: true,
  },
  {
    id: 3,
    title: "Laptop Repair Service",
    price: "Starting ₹499",
    location: "Bangalore",
    category: "Services",
    image: "/images/ads/laptop.png",
    posted: "Today",
    featured: true,
  },
  {
    id: 4,
    title: "Family Restaurant",
    price: "Special Offers",
    location: "Jaipur",
    category: "Restaurants",
    image: "/images/ads/restaurant.png",
    posted: "1 day ago",
    featured: true,
  },
];